# Generated by Django 6.0.5 on 2026-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
