# Generated by Django 6.0.5 on 2026-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('hero_name', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
